apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k6c8lc7up-python
  janus-idp.io/tekton: k6c8lc7up-python
  backstage.io/kubernetes-id: k6c8lc7up-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k6c8lc7up-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
